SRCS		= megaphone.cpp


FLAGS		= -Wall -Wextra -Wno-unused -Werror

NAME		= megaphone

all: 		$(NAME)

$(NAME):
			clang++ $(FLAGS) $(SRCS) -o $(NAME)

clean:		
			rm -rf $(NAME)

fclean:
			rm -rf $(NAME)
					 
